namespace PhyrosClassroom.Billing.Models;

public sealed record BillingEventRecord(
    Guid BillingId,
    string EventType,
    DateTimeOffset OccurredUtc,
    string BillingCode,
    string GivenName,
    string FamilyName,
    string? SourceSystem = null,
    string? SourceReference = null,
    DateOnly? BirthDate = null,
    string? GradeLevel = null,
    string? PrimaryGuardianName = null,
    string? PrimaryGuardianEmail = null,
    bool HasMedicalAlert = false,
    string? MedicalNotes = null,
    bool HasIep = false,
    IReadOnlyList<BillingDocumentReference>? Documents = null,
    IReadOnlyList<BillingRecordNote>? Notes = null,
    string SubjectId = "",
    Guid? SourceRegistrationId = null,
    string? SourceRegistrationStatus = null,
    DateTimeOffset? SourceRegistrationUpdatedAtUtc = null,
    string BillingName = "",
    bool WantsEmailNotifications = false,
    bool WantsSmsNotifications = false,
    string? OnboardingStatus = null,
    IReadOnlyList<BillingContact>? Contacts = null,
    IReadOnlyList<BillingStudent>? Students = null);
