namespace PhyrosClassroom.Billing.Models;

public sealed record BillingReadModel(
    Guid BillingId,
    string BillingCode,
    string GivenName,
    string FamilyName,
    DateTimeOffset RegisteredAtUtc,
    string? SourceSystem,
    string? SourceReference,
    DateOnly? BirthDate,
    string? GradeLevel,
    string? PrimaryGuardianName,
    string? PrimaryGuardianEmail,
    bool HasMedicalAlert,
    string? MedicalNotes,
    bool HasIep,
    IReadOnlyList<BillingDocumentReference> Documents,
    IReadOnlyList<BillingRecordNote> Notes,
    string SubjectId = "",
    Guid? SourceRegistrationId = null,
    string? SourceRegistrationStatus = null,
    DateTimeOffset? SourceRegistrationUpdatedAtUtc = null,
    string BillingName = "",
    bool WantsEmailNotifications = false,
    bool WantsSmsNotifications = false,
    string? OnboardingStatus = null,
    IReadOnlyList<BillingContact>? Contacts = null,
    IReadOnlyList<BillingStudent>? Students = null,
    DateTimeOffset? UpdatedAtUtc = null);
